# Generated by Django 5.2.6 on 2025-09-05 05:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='users',
            field=models.ManyToManyField(related_name='clients', through='projectmgmt.ClientMembership', through_fields=('client', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
